// examples/svelte/src/App.svelte
<script lang="ts">
    import {addPet, findPetsByStatus} from './api'

    const {ready, data: pets} = findPetsByStatus(fetch, {status: 'pending'})
    const r = findPetsByStatus(fetch, {status: '123'})

    let soldReady = undefined
    let soldPets = []

    function listSoldPets() {
        const req2 = findPetsByStatus(fetch, {status: 'sold'})
        soldReady = req2.ready
        req2.data.subscribe(v => soldPets = v)
    }
</script>

<main>
    {#await $ready}
        <div>Awaiting</div>
    {:then _}
        <div>Pets:</div>
        {#each $pets as pet}
            <div>pet: {pet.name}</div>
        {/each}
    {/await}

    <button on:click={listSoldPets}>List</button>
    <div>dynamic list:</div>
    {#if soldReady !== undefined}
        {#await $soldReady}
            <div>Awaiting</div>
        {:then _}
            <div>Pets:</div>
            {#each soldPets as pet}
                <div>pet: {pet.name}</div>
            {/each}
        {/await}
    {/if}
</main>

// examples/react/src/App.tsx
import React, { useState } from 'react'
import './App.css'

import { findPetsByStatus, addPet } from './api'

function App() {
  const [pets, setPets] = useState<string[]>([])

  async function onClick() {
    // !!! -> Types are working here
    const resp = await findPetsByStatus(fetch, { status: 'pending' })
    const newNames = resp.data.map((pet) => pet.name)
    setPets(newNames)

    // Uncomment this line to see the error:
    // await findPetsByStatus(fetch, { status: '123' })
  }

  async function createPet() {
    // const resp = await addPet(fetch, {id})
  }

  return (
    <div className='App'>
      {pets.map((name) => (
        <div key={name}>{name}</div>
      ))}
      <button onClick={onClick}>Fetch</button>
      <br />
      <button onClick={createPet}>Create pet</button>
    </div>
  )
}

export default App
